### PR TITLE
Ply reader

### PR DESCRIPTION
**Pull request by rezural**
This adds support for reading from ply files, of the format:

ply
format ascii 1.0
comment ...
element vertex 2440181
property float x
property float y
property float z
property float nx
property float ny
property float nz
end_header

### CODE REVIEW

**Comment by rezural** [comment]
BTW, this worked straight up amazing on 3 million point ply files. Resulting in this rendering:

https://www.youtube.com/watch?v=BbkCnsKESJU

Thankyou very much!

**Comment by w1th0utnam3** [comment]
Thanks! I'll make some small changes to the code

**Comment by w1th0utnam3** [comment]
If you have the time, maybe consider rewriting it using custom structs instead of using the HashMap based access? See e.g. https://github.com/Fluci/ply-rs/blob/master/examples/read_ply_to_structs.rs

**Comment by rezural** [comment]
Yeah, OK.

I was going to do this, but couldn't implement the trait on na::Vector3 directly (I wonder if there is a workaround for this?), and it seemed kinda invasive to add those structs just for one file format.

I will look at this in the next couple of days.

Thanks!

**Comment by w1th0utnam3** [comment]
Yeah, right. I think one could work around this by introducing a transparent newtype:
```rust
use nalgebra::Vector3;

#[repr(transparent)]
struct Vec3r(Vector3<Real>);
```
implementing the trait on this and then just transmuting the result of the parser from `Vec<Vec3r>` to `Vec<Vector3<Real>>`.

Although in general, I don't really like that the `PropertyAccess` trait does not support any error reporting as it only returns `Option`s and not `Results`s... But I guess missing or unparsable components of the vectors should usually not be a problem (as PLY files are usually created by other software that probably writes correct files), and in the rare case this happens, one can still give a respective message in the panic.

One thing we should make sure later though is to give meaningful errors if you try reading e.g. a file with doubles as a `f32` Vec.

**Pull request merged**
