### PR TITLE
Compute normals for TriMesh3d

### PR DESCRIPTION
**Pull request by whiterabbit42k**
I'm not sure if the normals computation is totally correct, but it looks ok-ish on my setup. It appears somewhat "pointy" at the vertices points sometimes, but this could be my shaders, not sure.

An alternative is to sum all the normals contributing to a vertices, and then have a second pass which normalizes every normal before returning? Not sure. Any feedback appreciated!

### CODE REVIEW

**Comment by whiterabbit42k** [comment]
@w1th0utnam3 let me know when you get a chance to review

**Comment by w1th0utnam3** [comment]
In general the best approach to compute normals using SPH data is to use the actual gradients of the fluid density as normals as this would result in much smoother normals. I want to implement this later but it doesn't have a high priority for me right now.

Interpolating the triangle normals to the vertices is an alternative that is probably much cheaper, so we could still add this functionality. In any case this should be something optional, people might not need the normals. I would prefer making this computation a method on the mesh e.g. `vertex_normals_into(&self, normals: &mut [Vector3<Real>])` (inside do the two-pass approach you described, use an assert to check that length of output is correct). You could also add a convenience method that returns a Vec.

Then, the user can call this if normals are needed. When I later add the other approach, we could make this e.g. an optional field on the `SurfaceReconstruction` and you could specify the strategy for the normal computation using an enum in the reconstruction parameters. But I would leave it as a method on the mesh for now, as long as we only have this simple approach.

Wrt. to your implementation, I think this should be the same as described here: https://www.iquilezles.org/www/articles/normals/normals.htm ?

**Comment by whiterabbit42k** [comment]
Ok I read the article, i am doing what the article describes, except I can remove the normalize in the loop; i think it's nice to leave the last normalization to shaders, since they'll likely do that anyway, and it saves a second normalization loop.

One reason I'd like to have the normals computed in the library is that it's done when computing the triangles, so it doesn't effectively loop the triangles twice, which can take some time for larger meshes.

Would it be acceptable to add a config enum like `normal_strategy: Option<NormalStrategy>` and an optional field like `normals: Option<Vec<Real>`, this way they're computed efficiently during triangulation if user asks for them, instead of another pass over the triangles if there's a method?

**Comment by w1th0utnam3** [comment]
I don't think the number of passes matters, especially as we are just looping over contiguous data and performing several arithmetic operations per item. Prefetching should take care of this. As long as you don't have several loops performing trivial operations per item or have expensive iterator chains and somehow prevent fusion of the loops, I don't think you need to worry about multiple passes.

Ok, so for your use case you basically just want to obtain the normal directions instead of the actual normals. Although this is quite specific to your application, we could still add this. I think I'll just add the following functions myself:
```rust
impl<R: Real> TriMesh3d<R> {
    pub fn vertex_normal_directions_inplace(&self, normal_directions: &mut [Vector3<R>]);
    pub fn vertex_normal_directions(&self) -> Vec<Vector3<R>>;
    pub fn vertex_normals_inplace(&self, normals: &mut [Unit<Vector3<R>>]);
    pub fn vertex_normals(&self) -> Vec<Unit<Vector3<R>>>;
}
```
The first one would be the one you need.

**Comment by w1th0utnam3** [comment]
See https://github.com/w1th0utnam3/splashsurf/commit/bd9ccb973bb8de6b4484e0c4f0d9efcc42df79e9

**Comment by whiterabbit42k** [comment]
yea commit looks good! i do recall seeing the in my patch a similar assert firing when normals != vertices but i don't see how that could have been happening now that i think about it, but i'll report back if if ind something.

**Comment by whiterabbit42k** [comment]
closing this since it's sufficient for my usecase

**Comment by w1th0utnam3** [comment]
> 
> 
> yea commit looks good! i do recall seeing the in my patch a similar assert firing when normals != vertices but i don't see how that could have been happening now that i think about it, but i'll report back if if ind something.

Yeah, please report back if you run into this. I think it could only happen if there is a vertex that does not belong to any triangle (vertices.len() > normals.len()) but that is not supposed to happen. The other way around, it would probably crash somewhere with out of bounds access before there are more normals than vertices (as this would indicate that a triangle refers to an invalid/non existent vertex).

In any case, thanks for contributing!

**Pull request closed without merging**
